OscProb: src/PMNS_OQS.cxx File Reference
PMNS_OQS.cxx File Reference
#include <cassert>
#include <complex>
#include <iostream>
#include <math.h>
#include <Eigen/Eigenvalues>
#include "PMNS_OQS.h"
Functions
bool is_same_array (array< int, 3 > input, array< int, 3 > test)
int get_permutation (array< int, 3 > input, array< int, 3 > test)
double get_f (array< int, 3 > indices)
Function Documentation
get_f()
double get_f (array< int, 3 > indices)
Definition at line 161 of file PMNS_OQS.cxx.
{
  int perm = 0;
  if ((perm = get_permutation(indices, {1, 2, 3}))) return perm;
  double value = 0.5;
  if ((perm = get_permutation(indices, {1, 4, 7}))) return perm * value;
  if ((perm = get_permutation(indices, {1, 6, 5}))) return perm * value;
  if ((perm = get_permutation(indices, {2, 4, 6}))) return perm * value;
  if ((perm = get_permutation(indices, {2, 5, 7}))) return perm * value;
  if ((perm = get_permutation(indices, {3, 4, 5}))) return perm * value;
  if ((perm = get_permutation(indices, {3, 7, 6}))) return perm * value;
  value = sqrt(3) / 2;
  if ((perm = get_permutation(indices, {4, 5, 8}))) return perm * value;
  if ((perm = get_permutation(indices, {6, 7, 8}))) return perm * value;
  return 0;
}
References get_permutation().
Referenced by OscProb::PMNS_OQS::SetDissipatorElement().
get_permutation()
int get_permutation (array< int, 3 > input, array< int, 3 > test)
Definition at line 150 of file PMNS_OQS.cxx.
{
  if (!is_same_array(input, test)) return 0;
  if (input[0] == test[0] && input[1] == test[1]) return 1;
  if (input[0] == test[1] && input[1] == test[2]) return 1;
  if (input[0] == test[2] && input[1] == test[0]) return 1;
  return -1;
}
References is_same_array().
Referenced by get_f().
is_same_array()
bool is_same_array (array< int, 3 > input, array< int, 3 > test)
Definition at line 143 of file PMNS_OQS.cxx.
{
  sort(input.begin(), input.end());
  sort(test.begin(), test.end());
  return input == test;
}
Referenced by get_permutation().